"""initial schema

Revision ID: a4fbdf04251d
Revises: 
Create Date: 2026-05-27 19:58:37.639559

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = 'a4fbdf04251d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('badge',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('iconUrl', sa.String(), nullable=True),
    sa.Column('criteria', sqlite.JSON(), nullable=True),
    sa.Column('tier', sa.Enum('BRONZE', 'SILVER', 'GOLD', 'SPECIAL', name='badgetier'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('displayName', sa.String(), nullable=True),
    sa.Column('passwordHash', sa.String(), nullable=True),
    sa.Column('avatarUrl', sa.String(), nullable=True),
    sa.Column('bio', sa.String(), nullable=True),
    sa.Column('role', sa.Enum('ARTIST', 'ADMIN', 'SUPER_ADMIN', name='userrole'), nullable=False),
    sa.Column('tier', sa.String(), nullable=True),
    sa.Column('totalLikesReceived', sa.Integer(), nullable=False),
    sa.Column('totalArtworks', sa.Integer(), nullable=False),
    sa.Column('isVerified', sa.Boolean(), nullable=False),
    sa.Column('isBanned', sa.Boolean(), nullable=False),
    sa.Column('createdAt', sa.DateTime(), nullable=False),
    sa.Column('updatedAt', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_username'), ['username'], unique=True)

    op.create_table('artwork',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('imageUrl', sa.String(), nullable=False),
    sa.Column('thumbnailUrl', sa.String(), nullable=True),
    sa.Column('medium', sa.String(), nullable=True),
    sa.Column('styleTags', sqlite.JSON(), nullable=True),
    sa.Column('authorId', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'PENDING', 'APPROVED', 'REJECTED', name='artworkstatus'), nullable=False),
    sa.Column('visibility', sa.Enum('PUBLIC', 'PRIVATE', 'UNLISTED', name='visibility'), nullable=False),
    sa.Column('likeCount', sa.Integer(), nullable=False),
    sa.Column('saveCount', sa.Integer(), nullable=False),
    sa.Column('viewCount', sa.Integer(), nullable=False),
    sa.Column('createdAt', sa.DateTime(), nullable=False),
    sa.Column('updatedAt', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['authorId'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('competition',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('theme', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('rules', sa.String(), nullable=True),
    sa.Column('prizes', sqlite.JSON(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'OPEN', 'VOTING', 'CLOSED', name='competitionstatus'), nullable=False),
    sa.Column('startDate', sa.DateTime(), nullable=True),
    sa.Column('endDate', sa.DateTime(), nullable=True),
    sa.Column('createdByAdminId', sa.Integer(), nullable=False),
    sa.Column('coverImageUrl', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['createdByAdminId'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('follow',
    sa.Column('followerId', sa.Integer(), nullable=False),
    sa.Column('followingId', sa.Integer(), nullable=False),
    sa.Column('createdAt', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['followerId'], ['user.id'], ),
    sa.ForeignKeyConstraint(['followingId'], ['user.id'], ),
    sa.PrimaryKeyConstraint('followerId', 'followingId'),
    sa.UniqueConstraint('followerId', 'followingId', name='uq_follow')
    )
    op.create_table('portfolio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userId', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('artworkIds', sqlite.JSON(), nullable=True),
    sa.Column('isPublic', sa.Boolean(), nullable=False),
    sa.Column('createdAt', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['userId'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('userId')
    )
    op.create_table('user_badge',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userId', sa.Integer(), nullable=False),
    sa.Column('badgeId', sa.Integer(), nullable=False),
    sa.Column('awardedAt', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['badgeId'], ['badge.id'], ),
    sa.ForeignKeyConstraint(['userId'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('competition_entry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('competitionId', sa.Integer(), nullable=False),
    sa.Column('userId', sa.Integer(), nullable=False),
    sa.Column('artworkId', sa.Integer(), nullable=False),
    sa.Column('communityVotes', sa.Integer(), nullable=False),
    sa.Column('judgeScore', sa.Float(), nullable=True),
    sa.Column('finalRank', sa.Integer(), nullable=True),
    sa.Column('createdAt', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['artworkId'], ['artwork.id'], ),
    sa.ForeignKeyConstraint(['competitionId'], ['competition.id'], ),
    sa.ForeignKeyConstraint(['userId'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('like',
    sa.Column('userId', sa.Integer(), nullable=False),
    sa.Column('artworkId', sa.Integer(), nullable=False),
    sa.Column('createdAt', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['artworkId'], ['artwork.id'], ),
    sa.ForeignKeyConstraint(['userId'], ['user.id'], ),
    sa.PrimaryKeyConstraint('userId', 'artworkId')
    )
    op.create_table('save',
    sa.Column('userId', sa.Integer(), nullable=False),
    sa.Column('artworkId', sa.Integer(), nullable=False),
    sa.Column('createdAt', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['artworkId'], ['artwork.id'], ),
    sa.ForeignKeyConstraint(['userId'], ['user.id'], ),
    sa.PrimaryKeyConstraint('userId', 'artworkId')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('save')
    op.drop_table('like')
    op.drop_table('competition_entry')
    op.drop_table('user_badge')
    op.drop_table('portfolio')
    op.drop_table('follow')
    op.drop_table('competition')
    op.drop_table('artwork')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_username'))
        batch_op.drop_index(batch_op.f('ix_user_email'))

    op.drop_table('user')
    op.drop_table('badge')
    # ### end Alembic commands ###
